# Generated by Django 4.2.5 on 2024-03-15 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_alter_habit_linked_habit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='frequency',
            field=models.CharField(choices=[('week', 'еженедельно'), ('day', 'ежедневно')], default='day', max_length=15, verbose_name='Переодичность'),
        ),
    ]
